# Generated by Django 4.1.5 on 2023-01-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linklist',
            old_name='desc',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='linklist',
            old_name='link',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='linklist',
            name='host',
        ),
        migrations.RemoveField(
            model_name='linklist',
            name='title',
        ),
    ]
